version: '2'

services:
  vatman:
    container_name: vatman
    image: vatman
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.project
    links:
      - mongodb
    volumes:
    # user needs to map this
     - /Users/Shared/vatman/:/Users/Shared/vatman/
  mongodb:
    build:
      context: .
      dockerfile: Dockerfile.mongodb
    container_name: mongodb_database
    image: mongodb
    restart: always
    ports:
     - 27017:27017
    volumes:
    # and this
     - /Users/Shared/vatman/data/mongodb/:/data/db
